Contact form
Asanchy/Portfolio-Mobile_Version_Skeleton_Setup pull request #3
Opened 2021-11-30 22:15 UTC by Asanchy

I this pull request I added the contact-me section and its form.

2021-11-30 23:36 UTC, Cathella requested changes
## 🟡 STATUS: CHANGES REQUIRED 🛑

### Hi @Asanchy ✋🏻, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## HIGHLIGHTS 💪🏻

✔️ Correct GitHub flow.
✔️ Good commit history.
✔️ All input fields have correct associated placeholder text and attributes
✔️ Linters correctly configured
✔️ Well written README file.
✔️ Form uses the action and method attribute to integrate with formspree service.
✔️ Form submits successfully with valid input values
✔️ All validations described in project description are working on form submission

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 23:36 UTC, Cathella commented on index.html
> +            </ul>
- [ ] Hi, great work on working on the project 💪🏻! So how about removing the form inputs and textarea from a `<ul>`? I am suggesting this because we are currently not dealing with a list. So it would be nice if you maintained a very simple structure for the form just to improve the overall code readability as seen below.

```
<form action="https://formspree.io/f/mayvwpkl" method="post">
  <input type="text" name="fullname" ...  required>
  <input type="email" name="email-address" ... required>
  <textarea name="message" ... required></textarea>
  <button type="submit">Get It Touch</button>
</form>
```

- [ ] The other suggestion is that it would be nice if you aligned the form children using flexbox because it aligns items in a clean simple way with less code 😄.

2021-11-30 23:36 UTC, Cathella commented on index.html
> +        <h2>I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.</h2>
- [ ] I have also noticed that the overall font that appears in your design is completely different from the required one. I think it would be nice importing the required fonts into your design correctly. This will actually move your design from basic to professional 😄.

2021-12-01 08:34 UTC, Rustamxon7 approved these changes
## Hi @Asanchy   👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://user-images.githubusercontent.com/69011963/133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7.png)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-12-01 08:34 UTC, Rustamxon7 commented on index.html
> +            <textarea name="message" id="message" maxlength="500" required>Enter text here</textarea>
- [ ] [OPTIONAL] Kindly accept my suggestion. In here `Enter text here` should be a place holder.


```suggestion
            <textarea name="message" id="message" maxlength="500" placeholder="Enter text here" required></textarea>
```

2021-12-01 08:39 UTC, merged