Desktop version
Asanchy/Portfolio-Mobile_Version_Skeleton_Setup pull request #4
Opened 2021-12-02 14:33 UTC by Asanchy

In this pull request, I added media queries for the desktop version.

2021-12-02 16:16 UTC, keneogu requested changes
Hi @Asanchy, 

Good job so far!

- All linters are passing
- You are following GitHub flow
- Good commit history
- Good PR description
- Your Design is looking good

There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [ ] Remove the links on your readme file that is not working e.g The MIT link.
- [ ] The getting started section of the readme file should show the steps to take to clone and run the project. Please fix this.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------

2021-12-02 16:16 UTC, keneogu commented on style.css
> +    border-top: 1px solid blue;
Your footer border-top color should be the same as the actual design. That is a gray line not blue. Please fix this.

2021-12-03 01:07 UTC, gabrielyea approved these changes
# Approved! :partying_face: :tada: 
Hi @Asanchy , 
![](https://media3.giphy.com/media/26vUDLOP9YIc8oxGg/giphy.gif)
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

PD. I left some comments on things you should try to fix!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 01:07 UTC, gabrielyea commented on README.md
> -This project is [MIT](./MIT.md) licensed.
[OPTIONAL]
I'm really sorry about the misunderstanding! :pray:  You are not supposed to remove the MIT link, you should fix it so it works! Having an MIT license is part of Microverses professional repo standard and it should be in all your projects! 

- [ ] Please add the MIT licenses for your future PRs.

2021-12-03 01:07 UTC, gabrielyea commented on index.html
>              <a href="#">See Project</a>
[OPTIONAL]
- [ ] Your See Project text is not placed correctly! Try to fix it so your portfolio looks professional! :muscle: 
![image](https://user-images.githubusercontent.com/28903404/144527242-5f925217-687c-4b9d-a192-d9e464a87cd9.png)

2021-12-03 05:08 UTC, merged